name: docuease_auth
description: A Docuease authentication app
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  url_launcher: ^6.2.4
  fluttertoast: ^8.1.2
  provider: ^6.0.5
  intl: ^0.18.1
  image_picker: ^1.1.0
  shared_preferences: ^2.0.15
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1   # Added for app icon

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/again.png"

flutter:
  uses-material-design: true
