name: docuease_auth
description: A Docuease authentication app

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0 # Keeping the higher version for http
  fluttertoast: ^8.1.2
  provider: ^6.0.5
  intl: ^0.18.1
  image_picker: ^1.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
